name: dask_course
channels:
  - conda-forge
dependencies:
  - dask
  - dask-image
  - dask-ml
  - pip
  - numpy
  - matplotlib
  - scikit-image
  - jupyter
  - jupyterlab
  - ipywidgets
  - pandas
  - nodejs
  - pip:
    - requests
    - dask_labextension
    - py7zr

#jupyter labextension install dask-labextension
#jupyter labextension install @jupyter-widgets/jupyterlab-manager
#jupyter labextension install @bokeh/jupyter_bokeh